### PR TITLE
Build should fail if compiler can't parse/compile source files

### PR DESCRIPTION
**Pull request by agabrys**
Hi,
I implemented:
- build failure on parse/compile source error
- extends warn/error message in ErrorReporter

Can you push this to v1.6.X and prepare release?

Regards

### CODE REVIEW

**Comment by agabrys** [comment]
Hi,
Is there any chance for release in the near future?

Regards

**Comment by Kidlike** [comment]
+1 for this...

When this plugin hits an error, the target file is empty. Thus the build should fail.

Or at least have a configuration "failOnError". Which should be defaulted to true imho.

Also it's a bit illogical to have ERROR logs in the maven build and the build passing...

**Comment by agabrys** [comment]
@Kidlike I see that the author did not have time to take care of it, so I will prepare the release of my fork in next week.

**Comment by Kidlike** [comment]
No rush by my side.. I created a groovy script that fails the build if a target file is empty :)

**Comment by agabrys** [comment]
Released.
```
<groupId>biz.gabrys.forks.com.samaxes.maven</groupId>
<artifactId>minify-maven-plugin</artifactId>
<version>1.6.3</version>
```

**Comment by samaxes** [comment]
Sorry guys for the lack of reply.
I'm back to the issues and PRs for the last version, but I'm not adding new features to v1.6.X.
Please use @agabrys fork if you need this feature or switch to v1.7.X.

**Pull request closed without merging**
